// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCXDY66U7YtrZInJ0eB_EHU-8DJkxUC8s',
    appId: '1:458009744588:web:d0714449ebf1b91cbc9e69',
    messagingSenderId: '458009744588',
    projectId: 'cineetec-23868',
    authDomain: 'cineetec-23868.firebaseapp.com',
    storageBucket: 'cineetec-23868.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDvIKzbEN_B4vx73QzFnnbQHVK7sp1fPY',
    appId: '1:458009744588:android:2561d12499f7268abc9e69',
    messagingSenderId: '458009744588',
    projectId: 'cineetec-23868',
    storageBucket: 'cineetec-23868.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxp7jHaOamuPbzphsoHlOE8XjkZ4TtadM',
    appId: '1:458009744588:ios:4c221f8b46c42d8bbc9e69',
    messagingSenderId: '458009744588',
    projectId: 'cineetec-23868',
    storageBucket: 'cineetec-23868.firebasestorage.app',
    iosBundleId: 'com.example.projetoBancoDados',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxp7jHaOamuPbzphsoHlOE8XjkZ4TtadM',
    appId: '1:458009744588:ios:4c221f8b46c42d8bbc9e69',
    messagingSenderId: '458009744588',
    projectId: 'cineetec-23868',
    storageBucket: 'cineetec-23868.firebasestorage.app',
    iosBundleId: 'com.example.projetoBancoDados',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCXDY66U7YtrZInJ0eB_EHU-8DJkxUC8s',
    appId: '1:458009744588:web:1c6c4c56b3ac7c0bbc9e69',
    messagingSenderId: '458009744588',
    projectId: 'cineetec-23868',
    authDomain: 'cineetec-23868.firebaseapp.com',
    storageBucket: 'cineetec-23868.firebasestorage.app',
  );

}